- Sources/TelemetryClient/TelemetryClient.swift
This is meant to avoid locking the main thread, because it's not actually affecting the UI, or something particular to the main thread, it should be safe to use a background thread instead
> Replace main queue for a background queue

- README.md
- Sources/TelemetryClient/TelemetryClient.swift
I cannot run a Release build for the simulator. This PR allows you to override the DEBUG/RELEASE block as needed for testing, but defaults to the old behaviour of blocking DEBUG builds.
To allow changing variables on the Configuration I had to make it a class instead of struct. This also gives you scope to add more options in the future.
> Added telemetryAllowDebugBuilds to the Configuration

- .gitignore
- ClientTester.xcodeproj/project.pbxproj
- ClientTester.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- ClientTester.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- ClientTester.xcodeproj/xcshareddata/xcschemes/SwiftClientTester-iOS.xcscheme
- ClientTester.xcodeproj/xcshareddata/xcschemes/SwiftClientTester-macOS.xcscheme
- ClientTester.xcodeproj/xcshareddata/xcschemes/TelemetryClient.xcscheme
- ClientTester.xcodeproj/xcshareddata/xcschemes/TelemetryClient_WatchOS.xcscheme
- ClientTester/.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
- ClientTester/Assets.xcassets/AccentColor.colorset/Contents.json
- ClientTester/Assets.xcassets/AppIcon.appiconset/Contents.json
- ClientTester/Assets.xcassets/Contents.json
- ClientTester/ClientTesterApp.swift
- ClientTester/ClientTester_macOS.entitlements
- ClientTester/ContentView.swift
- ClientTester/Package.swift
- ClientTester/iOS-Info.plist
- ClientTester/macOS-Info.plist
- ClientTester/tvOS-Info.plist
- ClientTester/watchOS-Extension-Info.plist
- ClientTester/watchOS-Info.plist
- Package.swift
- Sources/TelemetryClient/JSONFormatting.swift
- Sources/TelemetryClient/Signal.swift
- Sources/TelemetryClient/SignalCache.swift
- Sources/TelemetryClient/SignalManager.swift
- Sources/TelemetryClient/TelemetryClient.h
- Sources/TelemetryClient/TelemetryClient.swift
- Tests/TelemetryClientTests/TelemetryClientTests.swift
Ok, so there's a lot going on here.
I've added your local caching but fixed a few bugs. I also made it generic and not specific to `SignalPostBody` as was suggested on Twitter.
The cache will load any previously unsent signals from disk on initialisation.
I've refactored the `SignalPayload` into it's own struct.
There's a new `SignalManager` that handles the cache, timer etc..
`SignalManager` will send a new batch of signals every 10 seconds and also once at startup (If any previous signals exist)
Signals are sent in batches of 25. Attempting with 50 sometimes resulted in a `Payload Too Large` error.
There's no mitigation if sending 25 gives this error, so maybe increase the payload size server side just to make sure.
If signals fail to send, they will be added back to the queue, so if a …
> Added local and disk caching and test targets.

- Sources/TelemetryClient/TelemetryClient.swift
Client v1.1.0 is sending "SwiftClient 1.0.14"
Guessing the next release is 1.1.1!
> The wrong telemetryClientVersion is being sent

- README.md
- Sources/TelemetryClient/SignalManager.swift
App termination is an unreliable way to do background work on iOS. It is more reliable to use background/foreground events (as is already being done in watchOS and tvOS), so moving iOS code to use those paths as well.
Also one quick drive-by typo correction in README
> Write and load signal cache on background/foreground for iOS as well

- Sources/TelemetryClient/TelemetryClient.swift
Allows the user to choose whether they want a `newSessionBegan` signal
automatically sent each time the app is foregrounded/cold started
(when a new `sessionID` value is set). This new configuration property
defaults to `true` and must be set to `false` to prevent this signal
from being automatically sent.
> Add `sendNewSessionBeganSignal` configuration property

- Sources/TelemetryClient/Signal.swift
- If the current build is a debug build, SignalPayload.isTestFlight will now return false.
- Adds an `isDebug` payload key
> Differentiates DEBUG and TestFlight builds. Resolves #26

- Sources/TelemetryClient/TelemetryClient.swift
This PR adds a terminate method so that users can manually terminate the SDK early if desired.
This is useful for apps which allow their users to enable and disable data collection.
> Add terminate method

- Tests/TelemetryClientTests/TelemetryClientTests.swift
1. Initialise an UUID object with <YOUR-APP_ID> and crashes due to force unwrap. Fixed by supplying a valid UUID string for test.
2. isTestMode parameter missing
> Fix unit test

- Sources/TelemetryClient/SignalManager.swift
I forgot to remove shared from the new URLSession. This fixes!
> Fixes typo in URLSession

- Sources/TelemetryClient/CryptoHashing.swift
- Sources/TelemetryClient/SignalManager.swift
- Tests/TelemetryClientTests/CryptoHashingTests.swift
This makes sure that Apple devices use Apples newer CryptoKit library for generating a SHA256 hash for improved safety & performance.
Note that there was a need for double-checking with both `#if canImport(CryptoKit)` and `if #available` to ensure full compatibility with all platforms & devices. See also [here](https://forums.swift.org/t/conditionally-use-cryptokit/30138/3).
> Use Apples CryptoKit when available & fall back to CommonCrypto

- README.md
- tag-release.sh
I put all in a shell script so you could invoke it from anywhere if you decide to further automate things (locally or on the CI).
The script takes the new version as an argument and does 4 things:
1. Check that there are no uncommitted changes (otherwise fails).
2. Replace the version String in the SDK.
3. Commit the changes.
4. Tag the new commit.
I decided against a lint check because such a check would require the tag to be already available but you created the latest tag _after_ merging https://github.com/TelemetryDeck/SwiftClient/pull/70, so a lint check would run when it's already too late. The same problem exists with pre-commit hooks, as a tag can only be created _after_ the commit is made.
Fixes #57.
> Add tag-release.sh script for bumping version & tagging

- Sources/TelemetryClient/CryptoHashing.swift
- Sources/TelemetryClient/SignalManager.swift
Note that I skipped the app group based API (outlined [here](https://github.com/TelemetryDeck/SwiftClient/issues/12#issuecomment-1185511462)) as I figured very few would actually need it and those could simply override the default ID and store it in their shared app group defaults.
Also, I noticed lack of support for tvOS which supports identifierForVendor just like iOS according to Apples docs, so I added it. Plus some really minor docs improvements.
Lastly, because there was a lot of `#else` end even a nested `#if` I opted to indent them here inside the `defaultUserIdentifier` implementation. I did not search for other places and make them consistent everywhere, so if you dislike this inconsistency, feel free to re-indent. If you dislike indented `#if` in general, a compromise could be …
> Use a self-generated UUID as default ID on macOS + add tvOS support

- Sources/TelemetryClient/SignalManager.swift
- Sources/TelemetryClient/TelemetryClient.swift
- Tests/TelemetryClientTests/TelemetryClientTests.swift
Provides a way to opt out of analytics by settings the value of `analyticsDisabled` to `true` on the configuration.
I've considered just re-using the `swiftUIPreviewMode` and setting it to `true` whenever I want to opt out of sending signals, however as I'm storing the opt-out state in the App's user defaults, if I'm using this value during development it might emit events signals in SwiftUIPreviews as well. To not interfere with this preference I've create the above mentioned property.
Given this Pr is of interested and this feature will be implemented, I'm happy to also implement this in the Kotlin and JS SDKs.
> Implement `analyticsDisabled` to allow an opt out of analytics

- Sources/TelemetryClient/SignalManager.swift
Fixes #83
My assumption the crash is due to `self` ie SignalManager being deallocated  before completion handler for URLDataTask completes.
> Avoid runtime exception due to deallocated `unowned self`

- TelemetryClient.podspec
One hiccup -- it looks like the podspec is failing linting right now, because it looks like Cocoapods has a bug where linting of watchOS doesn't work: https://github.com/CocoaPods/CocoaPods/issues/11558
So, either (1) you could remove watchOS from the spec until this is fixed, or (2) when you push it to trunk, you could push it with the `--skip-import-validation` option (i.e., `pod trunk push --skip-import-validation TelemetryClient.podspec`).
I tested this podspec to integrate TelemetryDeck in my own app, and it seems to be working.
> Add a podspec for integration using Cocoapods.

- README.md
- Sources/TelemetryClient/LogHandler.swift
- Sources/TelemetryClient/SignalCache.swift
- Sources/TelemetryClient/SignalManager.swift
- Sources/TelemetryClient/TelemetryClient.swift
- Tests/TelemetryClientTests/LogHandlerTests.swift
- Tests/TelemetryClientTests/TelemetryClientTests.swift
By default, this will increase slightly the amount of logging that end clients see - however it is now far more configurable.
`showDebugLogs` has been deprecated with users being encouraged to use `logHandler`. The debug logs parameter is no longer used.
Closes #31
> Support customisable LogHandler

- Sources/TelemetryClient/Signal.swift
iOS and other Apple operating systems have a plethora of extension types all with a unique identifier which can be retrieved from the Info.plist for the current target.
A complete list of identifiers can be found here: https://developer.apple.com/documentation/bundleresources/information_property_list/nsextension/nsextensionpointidentifier
It is useful for developers to understand the source of the events, including whether it came from a widget, notification service, or other extension.
Closes #29 
⚠️  - this will upload raw identifiers which may not be immediately understandable by developers. It would be nice to enrich or _prettyify_ this data by rendering the likes of "com.apple.widgetkit-extension" as "Widget Extension" or "com.apple.usernotifications.content-extension" as …
> send extension identifier, if provided

- Sources/TelemetryClient/LogHandler.swift
- Sources/TelemetryClient/Signal.swift
- Sources/TelemetryClient/SignalCache.swift
- Sources/TelemetryClient/SignalEnricher.swift
- Sources/TelemetryClient/SignalManager.swift
- Sources/TelemetryClient/TelemetryClient.swift
- Tests/TelemetryClientTests/SignalPayloadTests.swift
- Tests/TelemetryClientTests/TelemetryClientTests.swift
Inspired by the Kotlin solution, you can now register enrichers to the configuration class.
Priority is in order of:
1. The metadata provided at the `.send` callsite
2. The metadata enrichers with the last enricher added having priority over the first
3. The default payload provided by this SDK
Closes #47
> Add support for metadata enrichers

- Sources/TelemetryClient/Signal.swift
Maybe I'm overseeing something, but this seems like a rather straightforward solution for that warning. 🧐
> Fix warning in `Signal.isAppStore` by using `#elseif`

- Sources/TelemetryClient/SignalManager.swift
As mentioned in https://github.com/TelemetryDeck/SwiftClient/issues/52, setting `waitsForConnectivity` causes all events that occur when there is no network connection to be lost when an app is quit.
I don't really see any need to check for network connection before calling send, with this change the dataTask will instantly fail and return an error (adding the signals back to the queue) since URLSession is checking the NWPath anyway.
> Remove `waitsForConnectivity`

- Sources/TelemetryClient/Signal.swift
Implements #115 
`DefaultSignalPayload` is in charge of computing the event's default payload like `appVersion`, `buildNumber` etc., which some clients may want to send along to sources besides the TelemetryDeck SDK (for example, a backend service with its own analytics implementation). This PR gives the payload public access to enable that.
> Give `DefaultSignalPayload` Public Access

- Sources/TelemetryClient/Signal.swift
- Sources/TelemetryClient/SignalManager.swift
- Sources/TelemetryClient/TelemetryClient.swift
- Tests/TelemetryClientTests/SignalPayloadTests.swift
- Tests/TelemetryClientTests/TelemetryClientTests.swift
Individual commits:
* [Update checks for temporary name xrOS to final visionOS](https://github.com/TelemetryDeck/SwiftClient/commit/f6d6eab72ee78f2afffc9092d44439a8ab636607)
* [Simple patch to ensure nothing is logged in SwiftUI preview mode](https://github.com/TelemetryDeck/SwiftClient/commit/fc6f2447f204317797525a40b6c2e3e054db2a82)
* [Refactor some function & property naming in SignalManager for more clarity + update docs](https://github.com/TelemetryDeck/SwiftClient/commit/389837d4e54570055a79b03013bbf09c54c04362) 
* [React to background/foreground changes on visionOS](https://github.com/TelemetryDeck/SwiftClient/commit/ed1a28152ee10a368890b37097da7f5fb16db542)
* [Add new method TelemetryClient.requestImmediateSync() for advanced churn …
> New force-sync method (load-capped) to track bad experiences that might lead users to leave/delete app (improved churn tracking)

- Sources/TelemetryClient/TelemetryClient.swift
Replace `fatalError(_:file:line:)` with `assertionFailure(_:file:line:)` to catch uninitialized `TelemetryManager.shared` without crashing in release builds.
See issue #112 for context.
> [TelemetryManager] Replace fatalError With assertionFailure

- .github/workflows/ci.yaml
- .swiftlint.yml
- Package.swift
- Sources/TelemetryClient/CryptoHashing.swift
- Sources/TelemetryClient/Signal.swift
- Sources/TelemetryClient/SignalEnricher.swift
- Sources/TelemetryClient/SignalManager.swift
- Sources/TelemetryClient/TelemetryClient.swift
- Sources/TelemetryClient/TelemetryDeck.swift
- Sources/TelemetryDeck/Exports.swift
- Sources/TelemetryDeck/PrivacyInfo.xcprivacy
- Tests/TelemetryClientTests/CryptoHashingTests.swift
- Tests/TelemetryClientTests/SignalPayloadTests.swift
- Tests/TelemetryClientTests/TelemetryClientTests.swift
This is a follow-up on #149 with the branch renamed to `grand-rename` and the decisions from https://github.com/TelemetryDeck/docs/pull/85 applied. This includes the changes from #149:
> In Swift, Locale.current represents the language and region the app is currently using. When an app is not localized to say German, for example, the identifier will not return de for the language even it's the users preferred language.
> 
> To make it easier for TelemetryDeck users to use a data-driven approach in deciding which languages to localize for next, it is important to add the preferred language of the user though, even if the app doesn't support it. It can also be useful to see just the app language or just the region, without them being clutched together in locale as in en_DE.
> 
> This PR …
> Make it easier to check for appLanguage, preferredLanguage, and region + grand rename

- README.md
- Sources/TelemetryClient/Presets/TelemetryDeck+Errors.swift
- Sources/TelemetryClient/Signal.swift
- Sources/TelemetryClient/TelemetryClient.swift
- Sources/TelemetryClient/TelemetryDeck.swift
Add convenience methods to SwiftSDK that allow the easier sending of navigational signals.
Fix #156
> Add Navigation events

- Sources/TelemetryClient/LogHandler.swift
For clients to be able to define their own log handler solutions, the initialiser must be made public.
Closes #123
> Define public init for LogHandler

- Sources/TelemetryClient/TelemetryClient.swift
Fixes https://github.com/TelemetryDeck/SwiftSDK/issues/177
> Fix missing session start upon app start on non-iOS platforms + avoid session restart when returning within 5 minutes

- .editorconfig
- Package.swift
- Sources/TelemetryClient/JSONFormatting.swift
- Sources/TelemetryClient/LogHandler.swift
- Sources/TelemetryClient/Presets/NavigationStatus.swift
- Sources/TelemetryClient/Presets/TelemetryDeck+Navigation.swift
- Sources/TelemetryClient/Signal.swift
- Sources/TelemetryClient/SignalCache.swift
- Sources/TelemetryClient/SignalEnricher.swift
- Sources/TelemetryClient/SignalManager.swift
- Sources/TelemetryClient/TelemetryClient.swift
- Tests/TelemetryClientTests/LogHandlerTests.swift
- Tests/TelemetryClientTests/TelemetryClientTests.swift
Implements #165.
Note that this is based off of the branch of #173 and therefore supersedes it. If this is merged first, #173 can be closed.
You might want to also check out my article in https://github.com/TelemetryDeck/docs/pull/98 to understand the changes better.
Also, it's probably a good idea if a few real-world customers give these changes a spin, either by including the `feature/data-race-safety` branch or on the `main` branch once this is merged. We should have some real-world testing before making a regular release.
> Add full data-race safety and enable strict concurrency checking for Swift 6 compatibility

- Sources/TelemetryClient/Signal.swift
- Sources/TelemetryClient/SignalEnricher.swift
- Sources/TelemetryClient/SignalManager.swift
- Tests/TelemetryClientTests/TelemetryClientTests.swift
TelemetryDeck's flagship SDK is still sending signals to the oldest version of the ingest API, which is an oversight that I'd like to correct quickly with the next release. 
This PR removes the code that converts a dictionary into colon-separated-strings because the v2 API actually accepts a dictionary for the payload parameter. It also sends data to the `/v2/` API endpoint that has been the canonical ingest API for literally a year.
> Update to Ingest API v2

- Sources/TelemetryClient/TelemetryClient.swift
This allows customers to access the hashed version of the user string they’ve set, in order to hand it over to other SDKs or webhooks.
> Add hashedDefaultUser property

- Sources/TelemetryClient/Presets/AnyIdentifiableError.swift
- Sources/TelemetryClient/Presets/TelemetryDeck+Errors.swift
This significantly improves the ease of use of the new error handling preset in the SwiftSDK. I wrote the helper added in this PR in my last app and it saved me a lot of repetitive code. I think it would make sense to ship as part of the SDK.
If merged, I can update the docs accordingly.
With this PR merged, rather than writing something like this every time I catch an error:
```swift
do {
// ...
} catch {
TelemetryDeck.errorOccurred(
id: "SeriesRenamer.loadItemFailed", 
category: .thrownException, 
message: error.localizedDescription
)
}
```
I can write this instead, saving unnecessary typing in many places:
```swift
do {
// ...
} catch {
TelemetryDeck.errorOccurred(
identifiableError: error.with(id: "SeriesRenamer.loadItemFailed")
)
}
```
> Add error wrapper to conform any error type to IdentifiableError

- Sources/TelemetryClient/Signal.swift
- Sources/TelemetryClient/SignalManager.swift
- Sources/TelemetryClient/TelemetryClient.swift
We’re usually sending old-style parameter names in parallel with the new-style parameter so that people who switch from SDK version 1 to 2 have an easier and smoother upgrade path.
However, this leads to problems with customers with lots of users, because they get twice as many session signals now.
Since not too many customers rely on session signals right now, I’d suggest we just do a hard switch in this case and deal with the slightly increased support load by offering customers who write in abou this updated queries.
> Remove the old “newSessionBegan” signal

- Sources/TelemetryDeck/Signals/SignalManager.swift
I tried different approaches to fix #137, even completely converting the entire `SignalCache` to an `actor`. But this caused problems with the `SignalManager` initializer requiring to be `async`, also it was not compatible with iOS 12.
But after a bit of research I came across the `beginBackgroundTask` API which seems to have been invented for exactly purposes like these: We want to write a file to disk exactly when the app is left by the user (and could be killed anytime).
According to the [docs](https://developer.apple.com/documentation/uikit/uiapplication/1623031-beginbackgroundtask):
> This method requests additional background execution time for your app. Call this method when leaving a task unfinished might be detrimental to your app’s user experience. For example, **_call this …
> Avoid blocking main thread for backupCache calls when leaving app

- Sources/TelemetryDeck/Helpers/LogHandler.swift
- Sources/TelemetryDeck/TelemetryClient.swift
- Tests/TelemetryDeckTests/LogHandlerTests.swift
Fixes https://github.com/TelemetryDeck/SwiftSDK/issues/131. Supersedes https://github.com/TelemetryDeck/SwiftSDK/pull/150.
Before | After
-|-
> Add support for OSLog and default to it on modern systems

- Sources/TelemetryDeck/Helpers/DictionaryExt.swift
- Sources/TelemetryDeck/TelemetryClient.swift
- Sources/TelemetryDeck/TelemetryDeck.swift
This fixes https://github.com/TelemetryDeck/SwiftSDK/issues/181 and it also fixes https://github.com/TelemetryDeck/SwiftSDK/issues/194.
> Add various default global options to reduce repetitive code

- Sources/TelemetryDeck/Signals/SignalManager.swift
Fixes https://github.com/TelemetryDeck/SwiftSDK/issues/185.
Apart from the keys specified in the task (which I assume to be server-side) I also added all default parameters we've been reporting and auto-creating insights for. Those should also not be overridden to ensure correct stats in our built-in charts.
> Log errors to console when reserved keys are being used by users

- Sources/TelemetryDeck/Presets/TelemetryDeck+Errors.swift
- Sources/TelemetryDeck/Presets/TelemetryDeck+Navigation.swift
- Sources/TelemetryDeck/Presets/TelemetryDeck+Purchases.swift
- Sources/TelemetryDeck/Signals/SignalManager.swift
- Sources/TelemetryDeck/TelemetryClient.swift
- Sources/TelemetryDeck/TelemetryDeck.swift
Fixes https://github.com/TelemetryDeck/SwiftSDK/issues/202.
> Avoid checking for reserved keys in internal signals being sent

- README.md
- Sources/TelemetryDeck/Signals/Signal.swift
I think it is useful to automatically send the colorScheme of the app to TelemetryDeck.
> Added colorScheme to default signal payload

- Sources/TelemetryDeck/TelemetryClient.swift
This should fix #191.
While I couldn't reproduce the problem as I can't run Xcode 15.0.1 on my Mac, it makes sense they are getting this error since the `nonisolated(unsafe)` was introduces in Swift 5.10 (see [SE-412](https://github.com/swiftlang/swift-evolution/blob/e273da0a1b7414fae9aaceb439715493de54a472/proposals/0412-strict-concurrency-for-global-variables.md)). It seems to be an oversight of Apple or the Swift engineers that I can't see the build error when building a package that is using Swift 5.9 toolset in later Swift versions.
> Replace 'nonisolated(unsafe)' from Swift 5.10+ with a more compatible approach

- Sources/TelemetryDeck/Signals/SignalManager.swift
- Sources/TelemetryDeck/TelemetryClient.swift
- Tests/TelemetryDeckTests/TelemetryDeckTests.swift
This fixes #190.
But please note that this adds a `@MainActor` requirement to the `hashedDefaultUser` because accessing the `identifierForVendor` on iOS needs access to `UIDevice.current`, which is only accessible on the main thread. Technically speaking, this is a breaking change, as users who migrated to Swift 6 may no longer be able to access `hashedDefaultUser` from a background thread without adding concurrency to their code.
Having that said, since the original PR states that this field was added to report the user ID to other systems, that kind of code should be done in concurrent contexts anyways and therefore for most users the fix would be as simple as adding the `await` keyword.
> Get 'hashedDefaultUser' working even without a custom user set

- Sources/TelemetryDeck/Signals/Signal.swift
- Sources/TelemetryDeck/Signals/SignalManager.swift
- Sources/TelemetryDeck/TelemetryClient.swift
Fixes https://github.com/TelemetryDeck/SwiftSDK/issues/215
Note that I also had to make a change in the logic to detect `layoutDirection` on macOS because it seems that `NSApp` is (surprisingly!) an implicitly-unwrapped Optional which caused tests to fail.
> Allow providing custom URLSession used internally for network requests

- Sources/TelemetryDeck/Helpers/DurationSignalTracker.swift
- Sources/TelemetryDeck/Helpers/SessionManager.swift
- Sources/TelemetryDeck/Signals/Signal.swift
- Sources/TelemetryDeck/Signals/SignalManager.swift
- Sources/TelemetryDeck/TelemetryClient.swift
- Sources/TelemetryDeck/TelemetryDeck.swift
This implements the first 3 [Pirate Metrics](https://github.com/TelemetryDeck/SwiftSDK/pull/223) subtasks:
Note that I have expanded upon the requested `dayOfWeek`, `dayOfMonth`, and `dayOfYear` fields and ended up with the following fields (the [requirements comment](https://github.com/TelemetryDeck/web/issues/1905#issuecomment-2368911503) was updated):
* `TelemetryDeck.Calendar.dayOfWeek` - Integer from 1 (Monday) to 7 (Sunday)
* `TelemetryDeck.Calendar.dayOfMonth` - Integer from 1 to 31, representing the day of the month
* `TelemetryDeck.Calendar.dayOfYear` - Integer from 1 to 366 (accounting for leap years), representing the day of the year
* `TelemetryDeck.Calendar.weekOfYear` - Integer from 1 to 53, representing the week of the year
* `TelemetryDeck.Calendar.monthOfYear` - Integer …
> Introduce automatic session tracking & enhance default parameters

- Sources/TelemetryDeck/Signals/Signal.swift
After engaging with the developer community, we decided to remove the two most sensitive accessibility parameters: VoiceOver and Switch Control, with the 7 more widely used parameters still available to make informed decisions.
We are very thankful for the honest and constructive feedback! ❤️
> Remove VoiceOver and SwitchControl addressing community feedback

- Sources/TelemetryDeck/TelemetryClient.swift
- Sources/TelemetryDeck/TelemetryDeck.swift
Fixes https://github.com/TelemetryDeck/SwiftSDK/issues/220
@winsmith The git diff for `TelemetryClient` looks like I changed more, but I actually only added the check `if configuration.reservedParameterWarningsEnabled` and indented the rest as-is inside it's body.
> Add new option to allow other SDKs to suppress reserved key warnings

- Sources/TelemetryDeck/Helpers/DurationSignalTracker.swift
- Sources/TelemetryDeck/TelemetryDeck.swift
This implements what we had discussed in our call recently, documented in the Pirate Metrics overview task as:
> Timed Actions (naming?)
>
> Todo Cihat: SDK has convenience functions for "named screen/function/activity has started" and "named screen/function/activity has finished". This creates a signal that sends "named screen/function/activity has taken x seconds"
I'm posting this as a separate PR because while it was discussed for Pirate Metrics, it's not directly related and can be published as a separate SDK improvement. I feel it could distract/confuse people if combined with Pirate Metrics.
I decided to call the APIs `startDurationSignal` and `stopAndSendDurationSignal`. These two functions are the only added public API. The duration will be reported in the parameter …
> Add new duration signal type where the SDK tracks duration & sends it

- Sources/TelemetryDeck/TelemetryDeck.swift
Fixes https://github.com/TelemetryDeck/SwiftSDK/issues/227.
> Prevent adding default parameter prefix to TelemetryDeck-internal params

- Sources/TelemetryDeck/TelemetryDeck.swift
Currently, the duration calculation is wrong leading to way too high values (factor 1_000_000 too high). This fixes that.
> Fix unit calculation for duration signals

- Sources/TelemetryDeck/Helpers/DurationSignalTracker.swift
- Sources/TelemetryDeck/TelemetryDeck.swift
> Add more options to new Duration Signals feature

- Sources/TelemetryClient/PrivacyInfo.xcprivacy
- Sources/TelemetryDeck/PrivacyInfo.xcprivacy
Hi,
Once we updated one of our apps to the latest version of the SDK, it got rejected by App Store Review for it was missing the `NSPrivacyAccessedAPICategoryUserDefaults` entry in the privacy manifest. We tracked it down to the TelemetryDeck SDK.
This PR addresses the issue by adding the missing description to both privacy manifests. Our app was accepted using a fork of the library with this change 🤩 .
Cheers,
K
PS: perhaps a step can be added to the GitHub workflow to check that? e.g. https://github.com/crasowas/app_store_required_privacy_manifest_analyser
> Adds NSPrivacyAccessedAPICategoryUserDefaults to privacy manifest
